import '../styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Providers from "@/providers/providers";
import React from "react";
import Header from "@/app/header";
import Footer from "@/app/footer";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {



    return (
        <html lang="en">
        <body>
        <Providers>
            <Header/>
            {children}
            <Footer/>
        </Providers>
        </body>
        </html>
    )
}
